name: 'CI-CD'
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install
      - name: Lintin
        run: pipenv run flake8
      - name: Packages vulnerabilities
        run: pipenv run safety check
